### ISSUE TITLE
Seems to be broken on Ubuntu 16.04

### ISSUE THREAD

**Issue by JimtotheB** [matisku/ansible-teamcity-server#11]
Due to it using an init script vs systemd.

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service teamcity-server: host"}

```

I don't know enough about TeamCity to write a unit file for it, I was just trying to get it running locally to evaluate it.

**Comment by matisku** [comment]
Hello. Thank you for a feedback. For now I have only implementation for SysVint and since Ubuntu 16.04 is using Systemd, it's not working. I'll prepare a fix soon.

**Comment by JimtotheB** [comment]
What OS is this known working on? I can just spin up a VM on that to get
going, the Docker options for team city aren’t working out so well for me.

-- 
Jim B

**Comment by matisku** [comment]
https://galaxy.ansible.com/matisku/teamcity-server/ Ubuntu Trusty

**Comment by matisku** [comment]
Done https://github.com/matisku/ansible-teamcity-server/pull/13
