### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by tmiller** [matisku/ansible-teamcity-server#5]
A lot of companies can't use this with out some form of license being associated with it.

**Comment by matisku** [comment]
What kind of licence you are referring to? 
Teamcity License or repo license?
For TeamCity you don't need to have license for 20 projects, and 3 agents.

**Comment by tmiller** [comment]
👍  Thanks for being responsive!

**Comment by ipsq** [comment]
MIT or GPL? Your meta main file and GitHub license file are in conflict.

**Comment by matisku** [comment]
@ipsq Fixed
